name: outlet
description: Application to help people voice out their struggles and communicate whats on their minds annonymously


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider:
  carousel_slider: ^4.0.0
  syncfusion_flutter_sliders: ^19.4.55
  internet_connection_checker:
  cached_network_image:
  flutter_svg:
  flutter_staggered_animations:
  logger:
  country_code_picker: ^2.0.2
  pinput: ^1.2.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  shared_preferences:
  firebase_core:
  firebase_storage:
  cloud_firestore:
  firebase_auth:
  flutter_launcher_icons:
  uuid:
  image:
  path_provider:
  timeago:
  share:
  url_launcher:
  camera:
  image_picker:
  audio_session:
  flutter_spinkit:
  permission_handler:
  expandable_text:
  file_picker:
  just_audio:
  pull_to_refresh:
  wakelock:
  system_settings:
  custom_timer:
  #firebase_app_check: ^0.0.6+18
  firebase_performance:
  intl_utils: ^2.1.0
  hive: ^2.2.3
  hive_flutter:
  record: ^4.3.3
  audioplayers: ^1.0.1
  firebase_messaging: ^13.0.0
  flutter_local_notifications:
  lottie: ^1.4.3
  dotted_border:
  flutter_audio_waveforms:



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  hive_generator:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.jpg"

# The following section is specific to Flutter.
flutter:

  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/logo/
    - assets/lotties/

  fonts:
  - family: black
    fonts:
      - asset: fonts/NunitoSans-Black.ttf
  - family: bold
    fonts:
      - asset: fonts/NunitoSans-Bold.ttf
  - family: extraBold
    fonts:
      - asset: fonts/NunitoSans-ExtraBold.ttf
  - family: extraLight
    fonts:
      - asset: fonts/NunitoSans-ExtraLight.ttf
  - family: regular
    fonts:
      - asset: fonts/NunitoSans-Regular.ttf
  - family: semiBold
    fonts:
      - asset: fonts/NunitoSans-SemiBold.ttf

flutter_intl:
  enabled: true
